" Colors

" enable syntax processing
syntax enable

" Spaces & Tabs
" number of visual spaces per TAB
set tabstop=2
" number of spaces in tab when editing
set softtabstop=2
set shiftwidth=2

" tabs are spaces
set expandtab

" UI Config
" show line numbers
set number

" show command in bottom bar
set showcmd

" highlight current line
" set cursorline

" load filetype-specific ident files
filetype indent on

" omni completion
filetype plugin on
set omnifunc=syntaxcomplete#Complete

" visual autocomplete for command menu
set wildmenu

" redraw only when we need to
set lazyredraw

" highlight mathing [{()}]
set showmatch

" Searching
" highlight matches
set hlsearch

" search as characters are entered
set incsearch

" enabe mouse scrolling
set mouse=a

" enabe copy to X clipborad buffer
set clipboard=unnamedplus

" forget about arrows
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" find something from current path
set path+=**
