#! /bin/sh

INTERNAL=eDP1

xrdb -merge .Xresources &
sxhkd &
killall -q compton &
sh ~/.config/polybar/launch.sh &
sh ~/.local/bin/java_nonreparenting_wm_hack.sh &
setxkbmap -option grp:lctrl_toggle -option caps:ctrl_modifier &
xset r rate 200 80 &
while pgrep -u $UID -x compton >/dev/null; do sleep 1; done
compton &
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh) &
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK &

if [[ $(hostname) == 'trustno1' ]]; then
  bspc monitor -d terminal web code documents chat files music extra
  bspc config window_gap            12
elif [[ $(hostname) == 'thinkpad' ]]; then
  monitors=($(xrandr | grep " connected "| awk '{ print$1 }'))

  if  [[ ${#monitors[@]} -eq 1 && ${monitors[0]} -eq INTERNAL ]]; then
    bspc monitor -d terminal web code documents chat files music extra
    xrdb -merge ~/.Xresources.d/hdpi &
  elif [ ${#monitors[@]} -eq 3 ]; then
    bspc monitor DP2-2 -d web documents chat files music extra
    bspc monitor DP2-3 -d terminal code
    sh ~/.screenlayout/two-screens-one-rotated.sh &
  fi
  
  nm-applet &
  bspc config window_gap 0
fi

betterlockscreen -w &

bspc config border_width          2

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc config focused_border_color $(xrdb -query | grep color4 | awk '{print $NF}')
bspc config normal_border_color $(xrdb -query | grep background | awk '{print $NF}')

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a Gimp desktop='extra' state=floating follow=on
bspc rule -a Chromium desktop='web'
bspc rule -a Google Chrome \(unstable\) desktop='web'
bspc rule -a Anki state=floating follow=on
bspc rule -a Gnome-pomodoro state=floating follow=on
bspc rule -a Zathura desktop='documents' state=tiled follow=on
